# Generated by Django 5.1.4 on 2025-02-19 16:27

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PenaltyOnCar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_penalty', models.PositiveIntegerField(blank=True, null=True, unique=True, validators=[django.core.validators.MaxValueValidator(500)], verbose_name='Номер штрафа')),
                ('pay_penalty', models.BooleanField(default=False, verbose_name='Оплата штрафа')),
                ('time_penalty', models.DateTimeField(auto_now_add=True, verbose_name='Время получения штрафа')),
            ],
            options={
                'verbose_name': 'Штраф',
                'verbose_name_plural': 'Штрафы',
            },
        ),
        migrations.AddField(
            model_name='parking',
            name='penalty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='penalty', to='parking_app.penaltyoncar', verbose_name='штраф'),
        ),
    ]
