# Generated by Django 5.1.4 on 2025-02-19 16:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking_app', '0002_penaltyoncar_parking_penalty'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, max_length=10, null=True, unique=True, verbose_name='Номер машины')),
            ],
        ),
        migrations.AlterField(
            model_name='parking',
            name='car_number',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parkings', to='parking_app.car'),
        ),
    ]
