# Generated by Django 5.1.4 on 2025-02-19 16:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking_app', '0003_car_alter_parking_car_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='car',
            options={'verbose_name': 'Машина', 'verbose_name_plural': 'Машины'},
        ),
        migrations.RemoveField(
            model_name='parking',
            name='penalty',
        ),
        migrations.AddField(
            model_name='car',
            name='penalty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cars', to='parking_app.penaltyoncar'),
        ),
    ]
