# Generated by Django 5.1.4 on 2025-02-20 19:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking_app', '0004_alter_car_options_remove_parking_penalty_car_penalty'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='penalty',
        ),
        migrations.AlterField(
            model_name='parking',
            name='car_number',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='car_number', to='parking_app.car'),
        ),
        migrations.CreateModel(
            name='CarPenalty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='car_penalty', to='parking_app.car')),
                ('penalty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='penalty_car', to='parking_app.penaltyoncar')),
            ],
        ),
    ]
