# Generated by Django 5.1.4 on 2025-01-18 19:30

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AutoBrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Марка авто')),
            ],
            options={
                'verbose_name': 'Марка авто',
                'verbose_name_plural': 'Марки авто',
            },
        ),
        migrations.CreateModel(
            name='AutoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Модель авто')),
            ],
            options={
                'verbose_name': 'Модель авто',
                'verbose_name_plural': 'Модели авто',
            },
        ),
        migrations.CreateModel(
            name='BaseAuto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('power', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(1000)], verbose_name='Мощность')),
                ('color', models.CharField(max_length=20, verbose_name='Цвет')),
                ('vin', models.CharField(max_length=20, unique=True, verbose_name='VIN')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auto_app.autobrand', verbose_name='Марка авто')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auto_app.automodel', verbose_name='Модель авто')),
            ],
            options={
                'verbose_name': 'Автомобиль',
                'verbose_name_plural': 'Автомобили',
            },
        ),
    ]
