# Generated by Django 5.1.4 on 2025-01-25 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0008_rename_image_category_images_post_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='images',
        ),
    ]
