# Generated by Django 5.1.4 on 2025-01-25 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0009_remove_category_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='news_app_images/', verbose_name='Изображение'),
        ),
    ]
